name: Theme Test

on:
  push:
    branches: [test, dev]
  pull_request:
    branches: [test, dev]

env:
  TZ: Asia/Shanghai

jobs:
  theme_test:
    name: Hexo build & deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout codes
      uses: actions/checkout@v2
      with:
        ref: 'test'

    - name: Setup node
      uses: actions/setup-node@v1
      with:
        node-version: '16.x'

    - name: Cache node modules
      uses: actions/cache@v1
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

    - name: Install dependencies
      run: |
        npm install -g hexo-cli
        npm install
        git clone https://github.com/blleng/hexo-theme-lx/ themes/lx
        rm themes/lx/_config.yml && mv theme.config.yml themes/lx/_config.yml
    - name: Generate files
      run: |
        hexo clean
        hexo generate
    - name: Deploy to gh-page🚀
      uses: JamesIves/github-pages-deploy-action@4.1.4
      with:
        branch: gh-page # The branch the action should deploy to.
        folder: public # The folder the action should deploy.
